### ISSUE TITLE
Latest version is broken: Could not resolve import "react".

### ISSUE THREAD

**Issue by THETCR** [modernweb-dev/storybook-prebuilt#105]
./src/manager.js imports React, but React is not bundled or defined as a dependency.

"Error while transforming node_modules\@web\storybook-prebuilt\manager.js: Could not resolve import "react"."

Verified the issue by using the open-wc initializer.

**Comment by peschee** [comment]
The last working version seems to be `0.1.28`. Every other version after that has this issue.

**Comment by abdonrd** [comment]
Friendly ping to @LarsDenBakker (I just see you create the latest version).
