### ISSUE TITLE
Watch flag doesn't seem to reload web components

### ISSUE THREAD

**Issue by TomzBench** [modernweb-dev/storybook-prebuilt#20]
Hello,

I run the `example-projects/storybook` project except that I added the "--watch" flag when running storybook.  I notice after doing this that the browser does reload, except the component does not update with the new changes. I think it might be related to the fact that the web components are still saved from prior to the code changes?  Is the `--watch` flag supported when running storybook-prebuilt?

**Comment by LarsDenBakker** [comment]
Watch is supported, I just tried it and it works fine for me. What kind of code edits are you making? Maybe you are changing properties overwritten by the story args?

**Comment by TomzBench** [comment]
I changed MyElement.js:33

```javascript
-- <h2>${this.title} Nr. ${this.counter}!</h2>
++ <h2>${this.title} foo ${this.counter}!</h2>
```
The browser reloaded as expected but the component still rendered the `Nr.`

**Comment by LarsDenBakker** [comment]
That works fine for me. Does the watch mode work for you in a regular project?

**Comment by TomzBench** [comment]
The issue is that the file watcher is not triggered correctly when using the VIM text editor. the solution that worked for me is adding the following to your .vimrc: 
```vimrc
set backupcopy=yes
```

See here for reference: https://github.com/webpack/webpack/issues/781#issuecomment-95523711 

Thanks @LarsDenBakker  for helping debug in chat.
