### ISSUE TITLE
Can put a demo to use storybook mdx format?

### ISSUE THREAD

**Issue by yhjhoo** [modernweb-dev/storybook-prebuilt#96]
I have referred this document, couldn't figure out a way to do it.

https://modern-web.dev/docs/dev-server/plugins/storybook/

**Comment by Westbrook** [comment]
Sorry for the delay on this, but it seems that MDX hasn't been working as expected for what looks like quite some time. I personally only use JS stories and a lot of other consumers of this project use MDJS, so it never got caught...until now. Looking at surfacing the fix here: https://github.com/modernweb-dev/web/pull/1828 Hopefully, that will get things working for you.

**Comment by Westbrook** [comment]
This should "just work" when leveraging: https://www.npmjs.com/package/@web/storybook-prebuilt/v/0.1.32 and https://www.npmjs.com/package/@web/dev-server-storybook/v/0.4.1

Check out https://github.com/modernweb-dev/web/blob/master/packages/dev-server-storybook/demo/wc/stories/Button-mdjx-docs.stories.mdx for an example.

Please let us know if you have any further issues or check out the `#open-wc` room in https://join.slack.com/t/lit-and-friends/shared_invite/zt-llwznvsy-LZwT13R66gOgnrg12PUGqw to discuss your situation with fellow members of the community.

**Comment by yhjhoo** [comment]
works for me, looks great now.
